# Generated by mkproject (Shell)
VERSION := 0.1.1
PROJECT_NAME := mkprj
LANG := go
LDFLAGS :=  -s -w -extldflags "-static"

build:
	go mod tidy && go build -ldflags="$(LDFLAGS)" -o ./$(PROJECT_NAME) main.go

install: build
	install -m 755 $(PROJECT_NAME) /usr/local/bin/
uninstall:
	rm -f /usr/local/bin/$(PROJECT_NAME)

pack:
	tar -czvf mkprj-v$(VERSION)-linux-amd64.tar.gz ./mkprj

clean:
	rm -f $(PROJECT_NAME) *.o
